#!/usr/bin/env python3
"""
Plot Intra-Kernel Profiler timeline trace summary (dur distributions).

Input: *_summary.json generated by `ikp_profile::HostSession::write_trace()`.
Output: per-region PNGs where x=dur, y=probability mass (histogram).
"""

import argparse
import json
import os
from typing import Dict, Any, List, Tuple

import numpy as np

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt


def _style():
    try:
        plt.style.use("seaborn-v0_8-whitegrid")
    except Exception:
        plt.style.use("ggplot")
    plt.rcParams.update(
        {
            "figure.facecolor": "white",
            "axes.facecolor": "white",
            "axes.edgecolor": "#222222",
            "axes.labelcolor": "#222222",
            "xtick.color": "#222222",
            "ytick.color": "#222222",
            "grid.alpha": 0.25,
            "font.size": 11,
            "axes.titlesize": 13,
            "axes.titleweight": "bold",
        }
    )


def _safe_name(s: str) -> str:
    out = []
    for c in s:
        if c.isalnum() or c in ["_", "-", "."]:
            out.append(c)
        else:
            out.append("_")
    return "".join(out).strip("_") or "region"


def _hist_to_xy(hist: Dict[str, Any]) -> Tuple[np.ndarray, np.ndarray, float]:
    bins = int(hist.get("bins", 0))
    lo = float(hist.get("min", 0.0))
    hi = float(hist.get("max", 0.0))
    prob = np.asarray(hist.get("prob", []), dtype=np.float64)
    if bins <= 0 or prob.size == 0:
        return np.zeros((0,), dtype=np.float64), np.zeros((0,), dtype=np.float64), 0.0
    if prob.size != bins:
        # Be tolerant: truncate/pad.
        if prob.size > bins:
            prob = prob[:bins]
        else:
            prob = np.pad(prob, (0, bins - prob.size), mode="constant", constant_values=0.0)
    if hi > lo:
        width = (hi - lo) / float(bins)
        centers = lo + (np.arange(bins, dtype=np.float64) + 0.5) * width
        return centers, prob, float(width)

    # Degenerate distribution: min == max (all samples at one value).
    # Matplotlib requires a numeric bar width; passing None can produce dtype/object
    # and fail inside Axes.bar. Use a small, scale-aware fallback width.
    center = lo  # == hi
    width = max(abs(center) * 0.02, 1e-6)
    centers = np.full((bins,), center, dtype=np.float64)
    return centers, prob, float(width)


def plot_one(region: Dict[str, Any], out_dir: str, logx: bool = False):
    rid = region.get("region")
    name = str(region.get("name", rid))
    hist = region.get("hist", {})
    x, p, width = _hist_to_xy(hist)

    if x.size == 0:
        return None

    _style()
    fig, ax = plt.subplots(figsize=(7.5, 3.8))
    # Always pass a numeric width (see _hist_to_xy for degenerate fallback).
    ax.bar(x, p, width=float(width), align="center", alpha=0.85, edgecolor="none")
    ax.set_xlabel("dur")
    ax.set_ylabel("probability")
    ax.set_title(f"region {rid}: {name}")
    if logx:
        ax.set_xscale("log")
    ax.margins(x=0.01)

    out_name = f"trace_dist_region{rid}_{_safe_name(name)}.png"
    out_path = os.path.join(out_dir, out_name)
    fig.tight_layout()
    fig.savefig(out_path, dpi=160)
    plt.close(fig)
    return out_path


def plot_overlay(regions: List[Dict[str, Any]], out_dir: str, logx: bool = False):
    # Overlay probability masses using step curves (avoid stacked bars).
    _style()
    fig, ax = plt.subplots(figsize=(8.5, 4.2))
    for r in regions:
        rid = r.get("region")
        name = str(r.get("name", rid))
        hist = r.get("hist", {})
        x, p, width = _hist_to_xy(hist)
        if x.size == 0:
            continue
        # Convert prob-mass bars to a step curve (bin edges).
        lo = float(hist.get("min", 0.0))
        hi = float(hist.get("max", 0.0))
        bins = int(hist.get("bins", len(p))) if hist.get("bins", None) is not None else int(len(p))
        if bins <= 0:
            continue
        bins = min(bins, int(len(p)))
        p = p[:bins]
        if hi > lo:
            edges = np.linspace(lo, hi, bins + 1, dtype=np.float64)
        else:
            # Degenerate range: fabricate equally spaced edges around the point.
            w = float(width) if width > 0 else max(abs(lo) * 0.02, 1e-6)
            edges = lo + (np.arange(bins + 1, dtype=np.float64) - 0.5 * bins) * w
        y = np.concatenate([p, [p[-1]]])  # last value for closing (len == bins+1)
        ax.step(edges, y, where="post", linewidth=1.4, alpha=0.9, label=f"{rid}:{name}")
    ax.set_xlabel("dur")
    ax.set_ylabel("probability (per-bin mass)")
    ax.set_title("dur distribution overlay (all regions)")
    if logx:
        ax.set_xscale("log")
    ax.legend(loc="best", fontsize=8, ncol=1)
    fig.tight_layout()
    out_path = os.path.join(out_dir, "trace_dist_overlay.png")
    fig.savefig(out_path, dpi=160)
    plt.close(fig)
    return out_path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--summary", default="", help="*_summary.json path")
    ap.add_argument("--blocks_dir", default="", help="directory containing block_*.json (from *_block_region_dists/)")
    ap.add_argument("--out_dir", default="", help="output directory (default: alongside summary)")
    ap.add_argument("--logx", action="store_true", help="log-scale x axis")
    ap.add_argument("--regions", default="", help="comma-separated region ids to plot (default: all)")
    args = ap.parse_args()

    if bool(args.summary) == bool(args.blocks_dir):
        raise SystemExit("provide exactly one of --summary or --blocks_dir")

    if args.summary:
        with open(args.summary, "r", encoding="utf-8") as f:
            data = json.load(f)

        out_dir = args.out_dir or os.path.dirname(os.path.abspath(args.summary)) or "."
        os.makedirs(out_dir, exist_ok=True)

        regions = data.get("regions", [])
        if args.regions.strip():
            want = set(int(x) for x in args.regions.split(",") if x.strip())
            regions = [r for r in regions if int(r.get("region", -1)) in want]

        out_paths = []
        for r in regions:
            p = plot_one(r, out_dir=out_dir, logx=args.logx)
            if p:
                out_paths.append(p)
        if regions:
            out_paths.append(plot_overlay(regions, out_dir=out_dir, logx=args.logx))

        for p in out_paths:
            if p:
                print(p)
        return

    # blocks_dir mode: iterate block_*.json and render into per-block subfolders.
    blocks_dir = os.path.abspath(args.blocks_dir)
    out_root = args.out_dir or blocks_dir
    os.makedirs(out_root, exist_ok=True)

    block_files = [
        os.path.join(blocks_dir, fn)
        for fn in sorted(os.listdir(blocks_dir))
        if fn.startswith("block_") and fn.endswith(".json")
    ]
    if not block_files:
        raise SystemExit(f"no block_*.json found in {blocks_dir}")

    want_regions = None
    if args.regions.strip():
        want_regions = set(int(x) for x in args.regions.split(",") if x.strip())

    for bf in block_files:
        with open(bf, "r", encoding="utf-8") as f:
            bdata = json.load(f)
        b = int(bdata.get("block", -1))
        regions = bdata.get("regions", [])
        if want_regions is not None:
            regions = [r for r in regions if int(r.get("region", -1)) in want_regions]
        bdir = os.path.join(out_root, f"block_{b}")
        os.makedirs(bdir, exist_ok=True)
        # Per-region plots
        for r in regions:
            p = plot_one(r, out_dir=bdir, logx=args.logx)
            if p:
                print(p)
        # Per-block overlay
        if regions:
            p = plot_overlay(regions, out_dir=bdir, logx=args.logx)
            if p:
                print(p)


if __name__ == "__main__":
    main()

